resources:
  - namespace.yml
  - secrets.yml
  - k8s/database/configmap.yml
  - k8s/database/statefulset.yml
  - k8s/database/service.yml
  - k8s/backend/gateway.yml
  - k8s/backend/auth.yml
  - k8s/backend/product-service.yml
  - k8s/backend/order-service.yml
  - k8s/backend/orders.yml
  - k8s/backend/user-service.yml
  - k8s/frontend/deployment.yml
